[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
dotenvy.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
